kind: pipeline
name: default

steps:
- name: test
  image: python:3.9
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - pip install poetry
  - poetry install
  - poetry run pytest --flake8 --cov=aiger_jani
  - poetry run codecov
